apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
  annotations:
    security.opendatahub.io/enable-auth: 'true' 
spec:
  autoConfig:
      detectorServiceLabelToMatch: trustyai/guardrails
      inferenceServiceToGuardrail: llm
  enableBuiltInDetectors: true
  enableGuardrailsGateway: false
  logLevel: DEBUG
  replicas: 1