FROM registry.access.redhat.com/ubi9/python-312:latest
WORKDIR /opt/app-root

COPY . .

RUN pip install uv
RUN uv pip install --no-cache-dir -e .

# Set XDG environment variables to use /tmp (always writable) for garak to write to
ENV XDG_CACHE_HOME=/tmp/.cache
ENV XDG_DATA_HOME=/tmp/.local/share
ENV XDG_CONFIG_HOME=/tmp/.config
