{{- if .Values.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: trustyai
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
