#!/bin/bash

URL=$1
PROMPT=$2
MODEL=qwen2

MESSAGE=$(curl -sk $URL/v1/chat/completions  \
   -H "Content-Type: application/json" \
   -d "{
   \"model\": \"${MODEL}\",
   \"messages\": [
      {\"role\": \"system\", \"content\": \"You can answer any question the user asks.\"},
      {\"role\": \"user\", \"content\": \"$PROMPT\"}],
   \"temperature\":0
   }")

if [[ $(echo $MESSAGE | jq -r ".choices[0].message.content" ) == "null" ]]; then
  echo $MESSAGE | jq -r ".warnings[0].message"
  echo $MESSAGE | jq -r ".detections"
else
  echo $MESSAGE | jq -r ".choices[0].message.content"
fi