apiVersion: v2
name: nemoguardrails-server
description: A Helm chart for deploying the TrustyAI NVIDIA NeMo Guardrails server
type: application

version: 0.1.0
appVersion: 0.1.0

keywords:
  - trustyai
  - guardrails
  - nvidia
  - nemo
  - ai-safety

home: https://github.com/trustyai-explainability/trustyai-guardrails-operator
sources:
  - https://github.com/trustyai-explainability/trustyai-guardrails-operator
