replicaCount: 1

image:
  repository: quay.io/rgeada/nemo-debug
  tag: latest
  pullPolicy: Always

env:
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: "api-token-secret"
        key: "token"

route:
  enabled: false

envoyFilter:
  enabled: false
  gatewayNamespace: gateway-system
  gatewayName: mcp-gateway
