apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
spec:
  autoConfig:
      inferenceServiceToGuardrail: phi3
      detectorServiceLabelToMatch: trustyai/guardrails
  enableBuiltInDetectors: true
  enableGuardrailsGateway: true
  logLevel: DEBUG
  replicas: 1