apiVersion: v1
kind: Secret
metadata:
  name: my-storage-secret
type: Opaque
stringData:
  bucket: "tempo"
  endpoint: "http://minio:9000"
  access_key_id: "minioadmin"
  access_key_secret: "minioadmin"
