apiVersion: v1
kind: ConfigMap
metadata:
  name: guardrails-orchestrator-config
data:
  regexDetectorImage: 'quay.io/trustyai/regex-detector:latest'
  vllmGatewayImage: 'quay.io/trustyai/vllm-orchestrator-gateway:latest'