#file: noinspection YAMLSchemaValidation
kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-gateway
  labels:
    app: fmstack-nlp
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: 8032
    detectors:
      - name: regex_competitor
        input: true
        output: true
        detector_params:
          regex:    
            - \b(?i:orange|apple|cranberry|pineapple|grape)\b
      - name: hap
        input: true
        output: true
        detector_params: {}
    routes:
      - name: all
        detectors:
          - regex_competitor
          - hap
      - name: hap
        detectors:
          - hap
        fallback_message: "I'm sorry, I cannot help with that."
      - name: passthrough
        detectors: