apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"
  enableGuardrailsGateway: true
  guardrailsGatewayConfig: "fms-orchestr8-config-gateway"
  enableBuiltInDetectors: true
  otelExporter:
    metricsEndpoint: 'http://my-otelcol-test-collector.model-namespace.svc.cluster.local:4317'
    metricsProtocol: grpc
    otlpExport: 'metrics,traces'
    tracesEndpoint: 'http://tempo-my-tempo-stack-distributor.model-namespace.svc.cluster.local:4317'
    tracesProtocol: grpc
  replicas: 1

