apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"
  enableGuardrailsGateway: true
  guardrailsGatewayConfig: "fms-orchestr8-config-gateway"
  enableBuiltInDetectors: true
  replicas: 1
