kind: ConfigMap
apiVersion: v1
metadata:
  name: orchestrator-config
data:
  config.yaml: |
    chat_generation:
      service:
        hostname: phi3-predictor.model-namespace.svc.cluster.local
        port: 8080
    detectors:
      built_in:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap:
        type: text_contents
        service:
          hostname: guardrails-detector-ibm-hap-predictor.model-namespace.svc.cluster.local
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
---
#file: noinspection YAMLSchemaValidation
kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-config
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: 8032
    detectors:
      - name: built_in
        input: true
        output: true
        detector_params:
          regex:    
            - \b(?i:orange|apple|cranberry|pineapple|grape)\b
      - name: hap
        input: true
        output: true
        detector_params: {}
    routes:
      - name: all
        detectors:
          - built_in
          - hap
      - name: hap
        detectors:
          - hap
        fallback_message: "I'm sorry, I cannot help with that."
      - name: passthrough
        detectors:
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
spec:
  orchestratorConfig: "orchestrator-config"
  enableGuardrailsGateway: true
  guardrailsGatewayConfig: "gateway-config"
  enableBuiltInDetectors: true
  replicas: 1
