apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: nemo
spec:
  replicas: 4
  nemoConfigs:
    - name: custom-detectors
      default: true
      configMaps:
        - config-custom-detectors
  env:
    - name: LLM_API_BASE
      valueFrom:
        secretKeyRef:
          name: llm-secret
          key: api-base
    - name: LLM_MODEL_NAME
      valueFrom:
        secretKeyRef:
          name: llm-secret
          key: model-name
    - name: LLM_API_KEY
      valueFrom:
        secretKeyRef:
          name: llm-secret
          key: api-key
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: llm-secret
          key: tempo-endpoint
    - name: OTEL_SERVICE_NAME
      value: "nemo-guardrails"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_METRICS_EXPORTER
      value: "none"
