apiVersion: v1
kind: ServiceAccount
metadata:
  name: nemo-guardrails-service-account
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nemo-guardrails-service-account-view
subjects:
  - kind: ServiceAccount
    name: nemo-guardrails-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view