apiVersion: v1
kind: Secret
metadata:
  name: my-storage-secret
  namespace: trustyai-guardrails
type: Opaque
stringData:
  access_key_id: minioadmin
  access_key_secret: minioadmin  
  bucket: tempo
  endpoint: https://minio.trustyai-guardrails.svc.cluster.local:9000
